version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praxi_backend_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: praxi_backend_postgres
    environment:
      POSTGRES_DB: praxi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: praxi_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
